### ISSUE TITLE
Crash after "set-mode"

### ISSUE THREAD

**Issue by m0urs** [m0urs/arlo-fhem#1]
Oct 15 18:32:43 raspberrypi02 arlo-fhem[9673]: 2020-10-15 18:32:43 - arlo-fhem - Received command:  set-mode aktiviert
Oct 15 18:32:43 raspberrypi02 arlo-fhem[9673]: DEBUG:  set-mode aktiviert
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]: Traceback (most recent call last):
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:   File "/opt/fhem/arlo-fhem/arlo-fhem.py", line 167, in <module>
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:     base.mode = 'armed'
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 238, in mode
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:     _set_mode_v2_cb(1)
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 222, in _set_mode_v2_cb
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:     if body.get('success', False) is True or body.get('resource', '') == 'activeAutomations':
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]: AttributeError: 'NoneType' object has no attribute 'get'
Oct 15 18:33:43 raspberrypi02 systemd[1]: arlo-fhem.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 18:33:43 raspberrypi02 systemd[1]: arlo-fhem.service: Unit entered failed state.
Oct 15 18:33:43 raspberrypi02 systemd[1]: arlo-fhem.service: Failed with result 'exit-code'.
Oct 15 18:33:54 raspberrypi02 systemd[1]: Started Arlo-FHEM-Daemon.
Oct 15 18:33:55 raspberrypi02 arlo-fhem[4728]: 2020-10-15 18:33:55 - arlo-fhem - version 1.0
Oct 15 18:33:55 raspberrypi02 arlo-fhem[4728]: 2020-10-15 18:33:55 - arlo-fhem - Trying to connect  1  of  5
Oct 15 18:34:02 raspberrypi02 arlo-fhem[4728]: 2020-10-15 18:34:02 - arlo-fhem - CONNECTED

**Comment by m0urs** [comment]
Opened issue with upsteam repository: https://github.com/twrecked/pyaarlo/issues/45

**Comment by m0urs** [comment]
"Added parameter "refresh_devices_every=3" to Arlo login in order to prevent the Arlo connection to close.": This does NOT help. Error has appeared again.

**Comment by m0urs** [comment]
Fixed in upstream code.

**Comment by m0urs** [comment]
Fixed with https://github.com/m0urs/arlo-fhem/commit/bd5cc38643b6b3a52fb60e409f9947a257d8fe03
