### ISSUE TITLE
KeyError: '(modes:59G1865E007ED|activeAutomations)'

### ISSUE THREAD

**Issue by m0urs** [m0urs/arlo-fhem#11]
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]: Traceback (most recent call last):
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:   File "/opt/fhem/arlo-fhem/arlo-fhem.py", line 174, in <module>
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:     base.mode = 'aktiviert_tag'
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 239, in mode
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:     _set_mode_v2_cb(1)
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 221, in _set_mode_v2_cb
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:     body = self._arlo.be.post(AUTOMATION_PATH, params=params, raw=True, tid=tid, wait_for=None)
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:   File "/opt/fhem/arlo-fhem/pyaarlo/backend.py", line 646, in post
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:     return self._wait_for_transaction(tid, timeout)
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:   File "/opt/fhem/arlo-fhem/pyaarlo/backend.py", line 556, in _wait_for_transaction
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]:     response = self._requests.pop(tid)
Oct 28 08:43:20 raspberrypi02 arlo-fhem[18919]: KeyError: '(modes:59G1865E007ED|activeAutomations)'
Oct 28 08:43:20 raspberrypi02 systemd[1]: arlo-fhem.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 08:43:20 raspberrypi02 systemd[1]: arlo-fhem.service: Unit entered failed state.
Oct 28 08:43:20 raspberrypi02 systemd[1]: arlo-fhem.service: Failed with result 'exit-code'.

**Comment by m0urs** [comment]
Opend issue with upstream https://github.com/twrecked/pyaarlo/issues/50

**Comment by m0urs** [comment]
Just saw that this is not only with custom modes but also with built-in ones:

Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]: 2020-10-28 14:57:21 - arlo-fhem - Received command:  set-mode deaktiviert
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]: Traceback (most recent call last):
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:   File "/opt/fhem/arlo-fhem/arlo-fhem.py", line 158, in <module>
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:     base.mode = 'disarmed'
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 239, in mode
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:     _set_mode_v2_cb(1)
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 221, in _set_mode_v2_cb
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:     body = self._arlo.be.post(AUTOMATION_PATH, params=params, raw=True, tid=tid, wait_for=None)
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:   File "/opt/fhem/arlo-fhem/pyaarlo/backend.py", line 646, in post
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:     return self._wait_for_transaction(tid, timeout)
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:   File "/opt/fhem/arlo-fhem/pyaarlo/backend.py", line 553, in _wait_for_transaction
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]:     while mnow < mend and self._requests[tid] is None:
Oct 28 14:57:21 raspberrypi02 arlo-fhem[4764]: KeyError: '(modes:4RD3837TA2965|activeAutomations)'
Oct 28 14:57:21 raspberrypi02 systemd[1]: arlo-fhem.service: Main process exited, code=exited, status=1/FAILURE

**Comment by m0urs** [comment]
Partially fixed in https://github.com/m0urs/arlo-fhem/commit/bd5cc38643b6b3a52fb60e409f9947a257d8fe03

**Comment by m0urs** [comment]
Hopefully fully fixed in https://github.com/m0urs/arlo-fhem/commit/6949cb9e54994fcb9e48158a432a50df6a4fbed3
