### ISSUE TITLE
Crash   (OSError: [Errno 98] Address already in use)

### ISSUE THREAD

**Issue by m0urs** [m0urs/arlo-fhem#3]
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]: 2020-10-18 21:47:02 - arlo-fhem - Received command:  get-mode
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]: DEBUG:  get-mode
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]: 2020-10-18 21:47:02 - arlo-fhem - Send FHEM command:  setreading Arlo_Cam.dum status-Home armed
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]: 2020-10-18 21:47:02 - arlo-fhem - Send FHEM command:  setreading Arlo_Cam.dum status-Bridge_AZMichael armed
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]: 2020-10-18 21:47:02 - arlo-fhem - Send FHEM command:  setreading Arlo_Cam.dum status-Bridge_AZSabine armed
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]: Traceback (most recent call last):
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]:   File "/opt/fhem/arlo-fhem/arlo-fhem.py", line 111, in <module>
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]:     s.bind((TCP_IP, TCP_PORT))
Oct 18 21:47:02 raspberrypi02 arlo-fhem[8117]: OSError: [Errno 98] Address already in use
Oct 18 21:47:02 raspberrypi02 systemd[1]: arlo-fhem.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 21:47:02 raspberrypi02 systemd[1]: arlo-fhem.service: Unit entered failed state.
Oct 18 21:47:02 raspberrypi02 systemd[1]: arlo-fhem.service: Failed with result 'exit-code'.

**Comment by m0urs** [comment]
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]: 2020-10-28 17:22:40 - arlo-fhem - Received command:  get-mode
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]: 2020-10-28 17:22:40 - arlo-fhem - Send FHEM command:  setreading Arlo_Cam.dum status-Home armed
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]: 2020-10-28 17:22:40 - arlo-fhem - Send FHEM command:  setreading Arlo_Cam.dum status-Bridge_AZMichael armed
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]: 2020-10-28 17:22:40 - arlo-fhem - Send FHEM command:  setreading Arlo_Cam.dum status-Bridge_AZSabine armed
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]: 2020-10-28 17:22:40 - arlo-fhem - Send FHEM command:  setreading Arlo_Cam.dum currentMode Aktiviert
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]: Traceback (most recent call last):
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]:   File "/opt/fhem/arlo-fhem/arlo-fhem.py", line 113, in <module>
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]:     s.bind((TCP_IP, TCP_PORT))
Oct 28 17:22:40 raspberrypi02 arlo-fhem[2202]: OSError: [Errno 98] Address already in use
Oct 28 17:22:41 raspberrypi02 systemd[1]: arlo-fhem.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 17:22:41 raspberrypi02 systemd[1]: arlo-fhem.service: Unit entered failed state.
Oct 28 17:22:41 raspberrypi02 systemd[1]: arlo-fhem.service: Failed with result 'exit-code'.
